# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b708255566b323a3a9fec8ef7fa8ace04b5eabe108aa099c1434c9c319daba24275a061d20660a71f6a12654de0506c7d79e703ef91f8c659960364abc117dc

test:
  secret_key_base: 25175ff8fd80a31142da81856e0dcabc422ea369d0a47233885ae5fd6f98476b1442e322df10e985c5a426b7a14ea093993878ac2e68984ae7da43a7a35d7f39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
